# build with -- docker image build -t my-centos .
# docker image build -t my-centos -f Dockerfile .

# stop all
# docker container stop $(docker container ls -a -q) &
# remove all
# docker container rm $(docker container ls -a -q) &

FROM centos:7
RUN yum install -y wget